# Generated by Django 4.0.2 on 2022-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_additional_info_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_info',
            field=models.CharField(max_length=50, verbose_name='Дополнительная информация'),
        ),
    ]
